services:
  - type: web
    name: products-backend
    env: docker
    plan: free
    repo:
      type: git
      # If you use Render's git integration, this will be auto-filled.
    # Root directory relative to the repository root where Render should run
    # Set this to the folder that contains the Dockerfile, pom.xml and src/
    root: ProductsBackend
    # When using Docker runtime, Render will use the repository Dockerfile.
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://products-backend-db:5432/products_backend_db"
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: products-backend-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: products-backend-db
          property: password

databases:
  - name: products-backend-db
    type: postgresql
    plan: starter
